name: FourStarLettings.com
favicon: null
layout_spectrum: 0.91515
typography_spectrum: 0.37965
title: Ai-Beta FourStarLettings.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7e9'
    - '#989898'
    - '#a6bbd0'
    - '#384623'
    - '#13190d'
  brandStrength: 0.75
  lightness: 0.6673246305435896
  saturation: 0.937371869571507
  rhythmicContrast: 0.5
purpose: []
